branch-defaults:
  master:
    environment: YourPiano-env
environment-defaults:
  YourPiano-env:
    branch: null
    repository: null
global:
  application_name: your-piano
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:ap-northeast-2::platform/Node.js running
    on 64bit Amazon Linux/4.8.1
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
